@echo off
:main
chcp 65001 >nul
mode 120, 30
color 09
title Webhook Spammer || Demox#9728
echo.
echo.
echo. 
echo                                           ██╗   ██╗ █████╗ ██████╗ ███████╗
echo                                           ██║   ██║██╔══██╗██╔══██╗██╔════╝
echo                                           ██║   ██║███████║██████╔╝█████╗  
echo                                           ╚██╗ ██╔╝██╔══██║██╔═══╝ ██╔══╝  
echo                                            ╚████╔╝ ██║  ██║██║     ███████╗
echo                                             ╚═══╝  ╚═╝  ╚═╝╚═╝     ╚══════╝   
echo                                               [+] Made by Demox#9728     
echo                                               [+] Vape Webhook Nuker
echo ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
echo. 
:spam
echo Welcome to Vape Webhook Nuker.
timeout 1 >nul
set /p message=Enter your message to spam through the webhook:
timeout 1 >nul
set /p webhook=Enter your webhook to spam:
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"%message%\"}" %webhook% 
echo Spamming Webhook...
cls
:del
set /p delwebhook=Delete Webhook [y/n]:
if %delwebhook% == y goto delete
if %delwebhook% == n goto s
:delete
curl -X DELETE %webhook%
echo Webhook Deleted, Would you like to get sent back to main? [y/n]
set /p c=Option:
if %c% == y goto h
if %c% == n goto l
:s
Echo Webhook Not Deleted, Would You like to exit? [y/n]
set /p v=Option:
if %v% == y goto y
if %v% == n goto x
:h
echo Sending back to main..
timeout 3 >nul
cls
goto main
:l
echo Exitting Vape Webhook Nuker..
timeout 3 >nul
exit
:y
echo Exitting Vape Webhook Nuker..
timeout 3 >nul
exit
:x
echo Sending back to main..
timeout 3 >nul
goto main